template:
  # TODO: Move to templates, so that we have set of configurations in one template!!!
  entity_type: 'node'
  source: 'views.view.content_search_api'
  fallback: 'testsite_builder.config_template.views_node_content_search_api.fallback'
  full_template_plugin: 'generic'
  pre_generate_clone:
    -
      from: 'display.default.display_options.fields.views_bulk_operations_bulk_form'
      to: 'display.default.display_options.fields.views_bulk_operations_bulk_form'
  post_generate_clone:
    -
      from: 'display.default.display_options.fields.search_api_operations'
      to: 'display.default.display_options.fields.search_api_operations'
  generate_per_field:
    -
      type: 'view_dependency_config'
      name: 'dependencies.config'
    -
      type: 'view_style_column'
      name: 'display.default.display_options.style.options.columns'
    -
      type: 'view_style_info'
      name: 'display.default.display_options.style.options.info'
    -
      type: 'view_field'
      name: 'display.default.display_options.fields'
    -
      type: 'view_filter'
      name: 'display.default.display_options.filters'
    -
      type: 'view_config_cache_tag'
      name: 'display.default.cache_metadata.tags'
    -
      type: 'view_config_cache_tag'
      name: 'display.page_1.cache_metadata.tags'
    -
      type: '_skip_sort_'
      name: 'display.default.display_options.sorts'
  generate_per_bundle:
    -
      type: 'view_search_api_bundle_path'
      name: 'display.page_1.display_options.path'
    -
      type: 'view_search_api_table'
      name: ''
  field_type_mapping:
    -
      type: 'string'
      source_field: 'title'
    -
      type: 'boolean'
      source_field: 'status'
      templates:
        -
          source: 'facets.facet.status'
          fallback: 'testsite_builder.config_template.views_node_content_search_api_facet.fallback'
          full_template_plugin: 'view_search_api_facet'
          pre_generate_clone: []
          post_generate_clone: []
          generate_per_field: []
          generate_per_bundle: []
        -
          source: 'block.block.thunder_admin_facet_status'
          fallback: 'testsite_builder.config_template.views_node_content_search_api_facet_block.fallback'
          full_template_plugin: 'view_search_api_facet_block'
          pre_generate_clone: []
          post_generate_clone: []
          generate_per_field: []
          generate_per_bundle: []
    -
      type: 'language'
      exclude_generation_type:
        - '_skip_sort_'
        - 'view_dependency_config'
        - 'view_style_column'
        - 'view_style_info'
        - 'view_field'
        - 'view_filter'
        - 'view_config_cache_tag'
    -
      type: 'metatag'
      exclude_generation_type:
        - '_skip_sort_'
        - 'view_dependency_config'
        - 'view_style_column'
        - 'view_style_info'
        - 'view_field'
        - 'view_filter'
        - 'view_config_cache_tag'
    -
      type: 'integer'
      exclude_generation_type:
        - '_skip_sort_'
        - 'view_dependency_config'
        - 'view_style_column'
        - 'view_style_info'
        - 'view_field'
        - 'view_filter'
        - 'view_config_cache_tag'
    -
      type: 'uuid'
      exclude_generation_type:
        - '_skip_sort_'
        - 'view_dependency_config'
        - 'view_style_column'
        - 'view_style_info'
        - 'view_field'
        - 'view_filter'
        - 'view_config_cache_tag'
    -
      type: 'entity_reference'
      exclude_generation_type:
        - '_skip_sort_'
        - 'view_dependency_config'
        - 'view_style_column'
        - 'view_style_info'
        - 'view_field'
        - 'view_filter'
        - 'view_config_cache_tag'
    -
      type: 'entity_reference_revisions'
      exclude_generation_type:
        - '_skip_sort_'
        - 'view_dependency_config'
        - 'view_style_column'
        - 'view_style_info'
        - 'view_field'
        - 'view_filter'
        - 'view_config_cache_tag'
    -
      type: 'string_long'
      exclude_generation_type:
        - '_skip_sort_'
        - 'view_dependency_config'
        - 'view_style_column'
        - 'view_style_info'
        - 'view_field'
        - 'view_filter'
        - 'view_config_cache_tag'
    -
      type: 'list_string'
      exclude_generation_type:
        - '_skip_sort_'
        - 'view_dependency_config'
        - 'view_style_column'
        - 'view_style_info'
        - 'view_field'
        - 'view_filter'
        - 'view_config_cache_tag'
    -
      type: 'created'
      exclude_generation_type:
        - '_skip_sort_'
        - 'view_dependency_config'
        - 'view_style_column'
        - 'view_style_info'
        - 'view_field'
        - 'view_filter'
        - 'view_config_cache_tag'
    -
      type: 'changed'
      exclude_generation_type:
        - '_skip_sort_'
        - 'view_dependency_config'
        - 'view_style_column'
        - 'view_style_info'
        - 'view_field'
        - 'view_filter'
        - 'view_config_cache_tag'
    -
      type: 'timestamp'
      exclude_generation_type:
        - '_skip_sort_'
        - 'view_dependency_config'
        - 'view_style_column'
        - 'view_style_info'
        - 'view_field'
        - 'view_filter'
        - 'view_config_cache_tag'
