template:
  entity_type: 'node'
  source: 'views.view.content'
  pre_generate_clone:
    -
      from: 'display.default.display_options.fields.node_bulk_form'
      to: 'display.default.display_options.fields.node_bulk_form'
  post_generate_clone:
    -
      from: 'display.default.display_options.fields.operations'
      to: 'display.default.display_options.fields.operations'
  generate_per_field:
    -
      type: 'view_dependency_config'
      name: 'dependencies.config'
    -
      type: 'view_style_column'
      name: 'display.default.display_options.style.options.columns'
    -
      type: 'view_style_info'
      name: 'display.default.display_options.style.options.info'
    -
      type: 'view_field'
      name: 'display.default.display_options.fields'
    -
      type: 'view_filter'
      name: 'display.default.display_options.filters'
    -
      type: 'view_config_cache_tag'
      name: 'display.default.cache_metadata.tags'
    -
      type: 'view_config_cache_tag'
      name: 'display.page_1.cache_metadata.tags'
  generate_per_view:
    -
      type: 'view_bundle_path'
      name: 'display.page_1.display_options.path'
  filed_type_mapping:
    - type: 'entity_reference'
      extra:
        settings:
          target_type: 'taxonomy_term'
      source_field: 'field_channel'
    -
      type: 'entity_reference'
      source_field: 'type'
    -
      type: 'string'
      source_field: 'title'
    -
      type: 'changed'
      source_field: 'changed'
    -
      type: 'created'
      source_field: 'created'
    -
      type: 'boolean'
      source_field: 'status'
    -
      type: 'timestamp'
      source_field: 'publish_on'
    -
      type: 'language'
      source_field: 'langcode'
