template:
  entity_type: 'node'
  source: 'search_api.index.content'
  fallback: 'testsite_builder.config_template.search_api_index.fallback'
  pre_generate_clone: []
  post_generate_clone: []
  generate_per_field:
    -
      type: 'view_dependency_config'
      name: 'dependencies.config'
    -
      type: 'search_api_field_settings'
      name: 'field_settings'
  generate_per_bundle: []
  field_type_mapping:
    -
      type: 'string'
      source_field: 'title'
    -
      type: 'boolean'
      source_field: 'promote'
    -
      type: 'entity_reference'
      soruce_field: 'type'
      match_rules:
        target_type: 'node_type'
    -
      type: 'entity_reference'
      soruce_field: 'field_channel'
      match_rules:
        target_type: 'taxonomy_term'
        cardinality: 1
    -
      type: 'entity_reference'
      soruce_field: 'field_tags'
      match_rules:
        target_type: 'taxonomy_term'
        cardinality: -1
    -
      type: 'changed'
      source_field: 'node_changed'
